### ISSUE TITLE
285 комикс

### ISSUE THREAD

**Issue by alexws54tk** [whatifrussian/img-src#3]
Ребяты, раз уж вы локализуете картинки, то [вот](https://commons.wikimedia.org/wiki/File:Webcomic_xkcd_-_Wikipedian_protester_RUS.png?uselang=ru) вам русская версия:

**Comment by uncleLem** [comment]
Not relevant, already exists at [xkcd.ru](xkcd.ru/285/)

**Comment by alexws54tk** [comment]
Надпись-то по-русски, а флаг на трибуне остался „пиндосский“.

**Comment by Totktonada** [comment]
Смысл адаптации в том, чтобы русский читатель воспринимал перевод так же, как читатель оригинала воспринимает оригинал. Место действия в данном случае не имеет значения, поэтому предлагаемое изменение адаптацией не является. Говоря неформально, это просто отсебятина — такого мы стараемся избегать.

**Comment by uncleLem** [comment]
Still not relevant to "What If?". Also not plausible since in Russian Federation he would be immediately seized because of unauthorized picket

**Comment by Fat-Zer** [comment]
>Still not relevant to "What If?". Also not plausible since in Russian Federation he would be immediately seized because of unauthorized picket

[заметка зануды]
строго говоря, он или часть митинга устроенного парнем на сцене (по всей видимости разрешённого), или одиночный пикетчик, на что де-юре разрешения не требуется.
