### ISSUE TITLE
Yet another «let's ...»

### ISSUE THREAD

**Issue by Fat-Zer** [whatifrussian/img-src#4]
может снова попробуем начать переводить?
собственно где нынче собираемся? в мейллисте давно глухо...

**Comment by Totktonada** [comment]
Все по-старому, см. ссылки в конце [Общих положений по переводу XKCD](https://docs.google.com/document/d/1CbAsTXjyU1Sl_F7pdjsJPyLXySXWc50kTraWipxYY3w) (сам документ содержит местами подустаревшую информацию).

Активность и инициатива только приветствуются.

**Comment by Fat-Zer** [comment]
дык, а ноту же вроде прикрыли, переводить то теперь где?

**Comment by Totktonada** [comment]
Отправил приглашение. Может попасть в спам.
